name       : krusader
version    : 2.7.1
release    : 4
source     :
    - https://cdn.download.kde.org/stable/krusader/2.7.1/krusader-2.7.1.tar.xz : d5c14d7e0698b84a1285efe7058074f760924d13d0823e1b5123fbe771907deb
license    : GPL-2.0-or-later
component  : desktop
summary    : Twin panel file manager for KDE
description: |
    Krusader is an advanced twin panel (commander style) file manager for KDE and other desktops in the *nix world, similar to Midnight or Total Commander.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - acl-devel
    - attr-devel
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - knotifications-devel
    - kparts-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - solid-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
