name       : krusader
version    : 2.8.0
release    : 10
source     :
    - https://download.kde.org/stable/krusader/2.8.0/krusader-2.8.0.tar.xz : 8e4cf05a9318b0bc1b0941811b988b2f2bb0c04a0d1e37998212a9190cf2c29a
homepage   : https://krusader.org/
license    : GPL-2.0-or-later
component  : desktop
summary    : Twin panel file manager for KDE
description: |
    Krusader is an advanced twin panel (commander style) file manager for KDE and other desktops in the *nix world, similar to Midnight or Total Commander.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libacl)
    - pkgconfig(libattr)
    - karchive-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - knotifications-devel
    - kparts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
